<?php

declare(strict_types = 1);

return [
    [
        "type_of"                  => "article",
        "id"                       => 1544,
        "title"                    => "The Line of Beauty172",
        "description"              => "Five dollar toast pour-over 8-bit gluten-free selvage try-hard. Stumptown listicle ennui plaid tacos...",
        "readable_publish_date"    => "Jan 12",
        "slug"                     => "the-line-of-beauty172-39d8",
        "path"                     => "/username382/the-line-of-beauty172-39d8",
        "url"                      => "http://localhost:3000/username382/the-line-of-beauty172-39d8",
        "comments_count"           => 0,
        "public_reactions_count"   => 0,
        "collection_id"            => null,
        "published_timestamp"      => "2023-01-11T16:00:22Z",
        "positive_reactions_count" => 0,
        "cover_image"              => "http://localhost:3000/assets/27-441873f471d98b5358beff7d47a211e58b9979c6453794f9a7abfd5709c33322.png",
        "social_image"             => "http://localhost:3000/assets/27-441873f471d98b5358beff7d47a211e58b9979c6453794f9a7abfd5709c33322.png",
        "canonical_url"            => "http://localhost:3000/username382/the-line-of-beauty172-39d8",
        "created_at"               => "2023-01-11T16:00:22Z",
        "edited_at"                => null,
        "crossposted_at"           => null,
        "published_at"             => "2023-01-11T16:00:22Z",
        "last_comment_at"          => "2023-01-11T16:00:22Z",
        "reading_time_minutes"     => 1,
        "tag_list"                 => [
            "discuss",
        ],
        "tags" => "discuss",
        "user" => [
            "name"             => "Ira Tanna \:/ West",
            "username"         => "username382",
            "twitter_username" => "twitter382",
            "github_username"  => "github382",
            "user_id"          => 3620,
            "website_url"      => null,
            "profile_image"    => "/uploads/user/profile_image/3620/3b3f8cf9-6517-4a48-aa69-95eeaf8b0456.jpeg",
            "profile_image_90" => "/uploads/user/profile_image/3620/3b3f8cf9-6517-4a48-aa69-95eeaf8b0456.jpeg",
        ],
        "organization" => [
            "name"             => "Klocko and Sons",
            "username"         => "org67",
            "slug"             => "org67",
            "profile_image"    => "/uploads/organization/profile_image/666/5431d3e5-2222-4881-8108-adecceb1cf6f.png",
            "profile_image_90" => "/uploads/organization/profile_image/666/5431d3e5-2222-4881-8108-adecceb1cf6f.png",
        ],
        "flare_tag" => [
            "name"           => "discuss",
            "bg_color_hex"   => "#000000",
            "text_color_hex" => "#ffffff",
        ],
    ],
    [
        "type_of"                  => "article",
        "id"                       => 1461235,
        "title"                    => "Meme Monday",
        "description"              => "Meme Monday!  Today's cover image comes from last week's thread.  DEV is an inclusive space! Humor in...",
        "readable_publish_date"    => "May 8",
        "slug"                     => "meme-monday-66l",
        "path"                     => "/ben/meme-monday-66l",
        "url"                      => "https://dev.to/ben/meme-monday-66l",
        "comments_count"           => 28,
        "public_reactions_count"   => 19,
        "collection_id"            => null,
        "published_timestamp"      => "2023-05-08T12:33:11Z",
        "positive_reactions_count" => 19,
        "cover_image"              => "https://res.cloudinary.com/practicaldev/image/fetch/s--us4WxI3I--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8746xyzk8h8idih9biq9.png",
        "social_image"             => "https://res.cloudinary.com/practicaldev/image/fetch/s--Wlq07HR_--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8746xyzk8h8idih9biq9.png",
        "canonical_url"            => "https://dev.to/ben/meme-monday-66l",
        "created_at"               => "2023-05-08T12:33:11Z",
        "edited_at"                => null,
        "crossposted_at"           => null,
        "published_at"             => "2023-05-08T12:33:11Z",
        "last_comment_at"          => "2023-05-08T19:25:43Z",
        "reading_time_minutes"     => 1,
        "tag_list"                 => [
            "discuss",
            "watercooler",
            "jokes",
        ],
        "tags" => "career, beginners, job, bestofdev",
        "user" => [
            "name"             => "Ben Halpern",
            "username"         => "ben",
            "twitter_username" => "bendhalpern",
            "github_username"  => "benhalpern",
            "user_id"          => 1,
            "website_url"      => "http://benhalpern.com",
            "profile_image"    => "https://res.cloudinary.com/practicaldev/image/fetch/s--nz-jndal--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/1/f451a206-11c8-4e3d-8936-143d0a7e65bb.png",
            "profile_image_90" => "https://res.cloudinary.com/practicaldev/image/fetch/s--Ea1OGrCb--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/1/f451a206-11c8-4e3d-8936-143d0a7e65bb.png",
        ],
        "flare_tag" => [
            "name"           => "discuss",
            "bg_color_hex"   => "#1ad643",
            "text_color_hex" => "#FFFFFF",
        ],
    ],
    [
        "type_of"                  => "article",
        "id"                       => 1458732,
        "title"                    => "What's Your Favorite Text Editor or Terminal Emulator?",
        "description"              => "When it comes to coding, your choice of text editor or terminal emulator can have a big impact on...",
        "readable_publish_date"    => "May 8",
        "slug"                     => "whats-your-favorite-text-editor-or-terminal-emulator-h91",
        "path"                     => "/codenewbieteam/whats-your-favorite-text-editor-or-terminal-emulator-h91",
        "url"                      => "https://dev.to/codenewbieteam/whats-your-favorite-text-editor-or-terminal-emulator-h91",
        "comments_count"           => 8,
        "public_reactions_count"   => 4,
        "collection_id"            => 22092,
        "published_timestamp"      => "",
        "positive_reactions_count" => 4,
        "cover_image"              => "https://res.cloudinary.com/practicaldev/image/fetch/s--7H4_sCeW--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8jab2sbu3ilbw9clsjqq.png",
        "social_image"             => "https://res.cloudinary.com/practicaldev/image/fetch/s--whj-j0pR--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8jab2sbu3ilbw9clsjqq.png",
        "canonical_url"            => "https://dev.to/codenewbieteam/whats-your-favorite-text-editor-or-terminal-emulator-h91",
        "created_at"               => "2023-05-05T17:53:47Z",
        "edited_at"                => null,
        "crossposted_at"           => null,
        "published_at"             => "2023-05-08T07:00:00Z",
        "last_comment_at"          => "2023-05-08T13:11:10Z",
        "reading_time_minutes"     => 1,
        "tag_list"                 => [
            "discuss",
            "beginners",
            "codenewbie",
        ],
        "tags" => "discuss, beginners, codenewbie",
        "user" => [
            "name"             => "Ben Halpern",
            "username"         => "ben",
            "twitter_username" => "bendhalpern",
            "github_username"  => "benhalpern",
            "user_id"          => 1,
            "website_url"      => "http://benhalpern.com",
            "profile_image"    => "https://res.cloudinary.com/practicaldev/image/fetch/s--nz-jndal--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/1/f451a206-11c8-4e3d-8936-143d0a7e65bb.png",
            "profile_image_90" => "https://res.cloudinary.com/practicaldev/image/fetch/s--Ea1OGrCb--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/1/f451a206-11c8-4e3d-8936-143d0a7e65bb.png",
        ],
        "organization" => [
            "name"             => "CodeNewbie",
            "username"         => "codenewbieteam",
            "slug"             => "codenewbieteam",
            "profile_image"    => "https://res.cloudinary.com/practicaldev/image/fetch/s--bKiNMMVU--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/organization/profile_image/2167/a575e4d1-42a8-471a-ab8a-a9240b002aa8.png",
            "profile_image_90" => "https://res.cloudinary.com/practicaldev/image/fetch/s--qt_66fM4--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/organization/profile_image/2167/a575e4d1-42a8-471a-ab8a-a9240b002aa8.png",
        ],
        "flare_tag" => [
            "name"           => "discuss",
            "bg_color_hex"   => "#1ad643",
            "text_color_hex" => "#FFFFFF",
        ],
    ],
];
